apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-consumer
  template:
    metadata:
      labels:
        app: my-consumer
    spec:
      containers:
      - name: consumer
        image: brwscr.azurecr.io/consumer:latest
